package edu.utk.loci.lodn.client;

enum MessageType 
{
	/* Values listed in ordinal value order for message types*/
	SESSION_OPEN_MSG_TYPE,
	SESSION_CLOSED_MSG_TYPE,
	SESSION_RESPONSE_MSG_TYPE,
	SESSION_LODNINFO_REQUEST_MSG_TYPE,
	SESSION_LODNINFO_MSG_TYPE,
	MKDIR_MSG,
	RMDIR_REQUEST,
	CREATEFILE_REQUEST,
	GETDIR_REQUEST,
	GETDIR_REPLY,
	ADDMAPPINGS_REQUEST,
	GETMAPPINGS_REQUEST,
	GETMAPPINGS_REPLY,
	GETSTAT_REQUEST,
	GETSTAT_REPLY,
	UNLINK_REQUEST,
	SETXATTR_REQUEST,
	GETXATTR_REQUEST,
	GETXATTR_REPLY,
	REMOVEXATTR_REQUEST,
	LISTXATTR_REQUEST,
	LISTXATTR_REPLY;
	
	static MessageType fromInteger(int ordinalValue)
	{
		return MessageType.values()[ordinalValue];
	}
}
